import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/Header";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

// Google Fonts
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

// Local Font
const itWeralionis = localFont({ src: "./ITWeralionis.otf", variable: "--font-it-weralionis" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={cn(geistSans.variable, geistMono.variable, itWeralionis.variable)}>
      <body className={cn("antialiased bg-black text-white")}>
        <SidebarProvider className="flex flex-col justify-center items-center">
          <Header />
          {children}
        </SidebarProvider>
      </body>
    </html>
  );
}
