import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider } from "../../@/components/ui/sidebar";

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

const itWeralionis = localFont({
  src: "./ITWeralionis.otf",
  variable: "--font-it-weralionis",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${itWeralionis.variable}`}
    >
      <body className="antialiased">
        <SidebarProvider>

          {children}
        </SidebarProvider>
      </body>
    </html>
  );
}
